dataset: "bbtautau"

preprocess:
  training:
    for_training: true
    overwrite: true
    raw_folder: "./RawData"
    processed_folder: &processed_folder "./NumpyData"
    sample_list:
      - "hhttbbSM_eval.pkl"
      - "ytautau_eval.pkl"
  evaluation:
    for_training: false
    overwrite: true
    raw_folder: "./RawData"
    processed_folder: *processed_folder
    split_save: true
    sample_list:
      - "hhttbbSM_eval.pkl"
      - "ytautau_eval.pkl"

sample:
  base_folder: *processed_folder
  tag: "bbtt"
  n_events: 10

  normalization:
    particle:
      mean: [ ]
      std: [ ]
    nu:
      mean: [ ]
      std: [ ]

evaluation:
  sample_tag: [ "bbtt" ]
  processed_folder: *processed_folder
  eval_save_path: "./Output"
  split_save: true
  model_path: "./Output/checkpoints/PET_bbtautau_8_local_layer_scale_token_baseline_generator.weights.h5"

features:
  nu:
    kinematic: [ "pt", "eta", "phi" ]
    particles:
      - truth_nu1
      - truth_nu2

  tau_vis:
    kinematic: [ "pt", "eta", "phi", "energy" ]
    extra: [ "nProng", "decayMode", "charge" ]
    particles:
      - Tau1
      - Tau2
    label: 1
    padding: 0
  jet:
    kinematic: [ "pt", "eta", "phi", "energy" ]
    extra: [ ]
    particles:
      - Jet_b1
      - Jet_b2
      - Jet_0
      - Jet_1
      - Jet_2
    label: 0
    padding: 3
  met:
    kinematic: [ "pt", "phi" ]
    particles:
      - met
  weight:
    event: "weight_mc"
    sample:
      hhttbbSM_eval: 0.1
      ytautau_eval: 1.0
      Ztt_eval: 0.1
      ttbar_dilep_eval: 0.0
      VBFhhttbbSM_eval: 0.0
  extra:
    - "eventNumber" # 1
    - "runNumber" # 1
    - "weight_mc" # 1
    - "mmc" # 4

training:
  batch_size: 2048
  epoch: 500
  lr: 0.0005
  lr_factor: 10

model:
  ckpt_save_path: "./Output"

  # automatically get from input data
  # num_feat: 10
  # num_jet: 6
  # num_classes: 2
  # num_part: 7

  # the probability of dropping a feature in the input data
  feature_drop: 0.1
  # the dims of the hidden layer
  projection_dim: 128
  #Use local embedding
  local: true
  # number of  the neighbors
  K: 2
  # number of  the local features
  num_local: 2
  # number of  the PET layers
  num_layers: 8
  # number of  the classification layer
  num_class_layers: 2
  # number of  the generator layer
  num_gen_layers: 3
  # number of  the Attention heads
  num_heads: 8
  # Drop feature probability
  drop_probability: 0.0
  # Dropout rate
  dropout: 0.1
  # Use simplified head model
  simple: false
  # Use layer scale in the residual connections
  layer_scale: true
  # the initial value of the layer scale
  layer_scale_init: 0.00001
  # Use talking head attention
  talking_head: false
  # Loss type to train the model
  mode: "generator"
  fine_tune: false
  use_mean: false