dataset: "pptautau"

preprocess:
  raw_folder: "./RawData"
  processed_folder: &processed_folder "./NumpyData"
  sample_list:
    - "rho_rho_recon_boost.pkl"
    - "pi_rho_recon_boost.pkl"

sample:
  base_folder: *processed_folder
  tag: "e_pi"

  tau_visible_number: 2
  normalization:
    particle:
      # pt, eta, phi, energy, charge, is_el, is_mu, is_charged_pion, is_neutral_particle
      mean: [ 2.470e+1, 0.0, 0.0, 6.949e+1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
      std: [ 1.750e+1, 1.0, 1.0, 1.192e+2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
    nu:
      # (nu1) px, py, pz, (nu2) px, py, pz
      mean: [ 2.198e-2, 1.831e-2, -4.410e-3, -1.366e-2, 3.675e-2, 1.322e-1 ]
      std: [ 1.569e+1, 1.582e+1, 4.252e+1, 1.825e+1, 1.823e+1, 5.234e+1 ]

model:
  ckpt_save_path: "./Output"

  # automatically get from input data
  # num_feat: 10
  # num_jet: 6
  # num_classes: 2
  # num_part: 7

  # the probability of dropping a feature in the input data
  feature_drop: 0.1
  # the dims of the hidden layer
  projection_dim: 128
  #Use local embedding
  local: true
  # number of  the neighbors
  K: 2
  # number of  the local features
  num_local: 2
  # number of  the PET layers
  num_layers: 8
  # number of  the classification layer
  num_class_layers: 2
  # number of  the generator layer
  num_gen_layers: 3
  # number of  the Attention heads
  num_heads: 8
  # Drop probability
  drop_probability: 0.0
  # Use simplified head model
  simple: false
  # Use layer scale in the residual connections
  layer_scale: true
  # the initial value of the layer scale
  layer_scale_init: 0.00001
  # Use talking head attention
  talking_head: false
  # Loss type to train the model
  mode: "generator"
  fine_tune: false
  use_mean: false